// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5Pc192cesTOTsZIzIYa49EHKWKxHERzQ',
    appId: '1:619358645550:web:0f9b87f0c0a1c972ff5ebf',
    messagingSenderId: '619358645550',
    projectId: 'mecuadra-d0584',
    authDomain: 'mecuadra-d0584.firebaseapp.com',
    databaseURL: 'https://mecuadra-d0584-default-rtdb.firebaseio.com',
    storageBucket: 'mecuadra-d0584.appspot.com',
    measurementId: 'G-E4CHMMK74R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnP7PoXyOAFwo4OKWo0YDTefdinTJzGLM',
    appId: '1:619358645550:android:82521b454f977ad8ff5ebf',
    messagingSenderId: '619358645550',
    projectId: 'mecuadra-d0584',
    databaseURL: 'https://mecuadra-d0584-default-rtdb.firebaseio.com',
    storageBucket: 'mecuadra-d0584.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFiaFRkkapLicTHO8oIIaRlSkcdW2-2o8',
    appId: '1:619358645550:ios:39b4fddd4b974983ff5ebf',
    messagingSenderId: '619358645550',
    projectId: 'mecuadra-d0584',
    databaseURL: 'https://mecuadra-d0584-default-rtdb.firebaseio.com',
    storageBucket: 'mecuadra-d0584.appspot.com',
    androidClientId: '619358645550-ms3fkd7i85orp86r8hprvtvip5pbf1ic.apps.googleusercontent.com',
    iosClientId: '619358645550-vlfp3r37gi7m2e3c76gq5dhr9jpq5q6p.apps.googleusercontent.com',
    iosBundleId: 'com.example.meCuadraUsers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFiaFRkkapLicTHO8oIIaRlSkcdW2-2o8',
    appId: '1:619358645550:ios:39b4fddd4b974983ff5ebf',
    messagingSenderId: '619358645550',
    projectId: 'mecuadra-d0584',
    databaseURL: 'https://mecuadra-d0584-default-rtdb.firebaseio.com',
    storageBucket: 'mecuadra-d0584.appspot.com',
    androidClientId: '619358645550-ms3fkd7i85orp86r8hprvtvip5pbf1ic.apps.googleusercontent.com',
    iosClientId: '619358645550-vlfp3r37gi7m2e3c76gq5dhr9jpq5q6p.apps.googleusercontent.com',
    iosBundleId: 'com.example.meCuadraUsers',
  );
}
